# Configuration data for RootsMagic related Python scripts. (ä)

[FILE_PATHS]

DB_PATH       = /PATH/TO/YOUR/DATABASE.rmtree
RMNOCASE_PATH = /PATH/TO/unifuzz.so

[CREDENTIALS]

FS_USERNAME = 
FS_PASSWORD = 
