# Configuration data for RootsMagic related Python scripts. (ä)

[FILE_PATHS]
DB_PATH         = TEST.rmtree

REPORT_FILE_DISPLAY_APP  = C:\Windows\system32\Notepad.exe
REPORT_FILE_PATH  = Report_ExternalFilesInfo.txt


[OPTIONS]

