# Configuration data for MiniReport

[FILE_PATHS]

DB_PATH = C:\Users\rotter\Genealogy\GeneDB\Otter-Saito.rmtree
REPORT_FILE_PATH = MiniReport.txt
REPORT_FILE_DISPLAY_APP = C:\Windows\System32\notepad.exe

[OPTIONS]

AUTO_CLOSE = on
AUTO_CLOSE_DELAY_MS = 3000
