# Configuration data for RootsMagic related Python scripts. (ä)

[FILE_PATHS]
DB_PATH                  = TEST.rmtree

REPORT_FILE_PATH         = Report_MergeDuplicateFamilyRecords.txt

REPORT_FILE_DISPLAY_APP  = C:\Windows\System32\Notepad.exe

