# Configuration data for RootsMagic related Python scripts. (ä)

[FILE_PATHS]
DB_PATH = ..\Places from FS\DB\TEST-Places from FS.rmtree
# DB_PATH                  = C:\Users\rotter\Genealogy\GeneDB\Otter-Saito.rmtree
# DB_PATH                  = TEST.rmtree
REPORT_FILE_PATH         = Report_NormalizeNoteLineEndings.txt
REPORT_FILE_DISPLAY_APP  = C:\Windows\System32\Notepad.exe

[OPTIONS]
# EOL_STYLE  = LF    (\n)  or  CRLF  (\r\n)
EOL_STYLE    = CRLF
# Add the selected line ending to every non-empty Note value.
ENSURE_FINAL_EOL = true
MAKE_CHANGES = true
