# DEV_RM-Python-config

[FILE_PATHS]

DB_PATH  = C:\Users\rotter\dev\Genealogy\repo Genealogy-scripts\Move citations between person and name\DB\TEST-Move citations between person and name.rmtree

REPORT_FILE_PATH         = REPORT move citations.txt
REPORT_FILE_DISPLAY_APP  = C:\Users\rotter\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
  --new-window

#REPORT_FILE_DISPLAY_APP  = C:\Windows\System32\notepad.exe


[OPTIONS]

