# DEV_RM-Python-config

[FILE_PATHS]

DB_PATH                  = DB\TEST-Merge duplicate family records.rmtree

REPORT_FILE_PATH         = .\Report_MergeDuplicateFamilyRecords.txt

#REPORT_FILE_DISPLAY_APP  = C:\Windows\System32\notepad.exe
REPORT_FILE_DISPLAY_APP  = C:\Users\rotter\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
  --new-window

