# DEV_RM-Python-config

[FILE_PATHS]

DB_PATH                  = DB\TEST-PlaceTable Editor.rmtree
RMNOCASE_PATH = C:\Users\rotter\Genealogy\GeneDB\SW\SQLite extensions\unifuzz64.dll

REPORT_FILE_PATH         = .\Report_Places.txt

#REPORT_FILE_DISPLAY_APP  = C:\Windows\System32\notepad.exe
REPORT_FILE_DISPLAY_APP  = C:\Users\rotter\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd
  --new-window

[OPTIONS]
PLACETYPE                = 0
PLACE_FILTER             = Deutschland
PLACE_FILTER_NOT         = 
PLACE_FILTER_NOT_NOTE    = _SKIP|FSPID
PLACE_FILTER_NOT_NAME    = ~




